# Generated by Django 4.0.5 on 2022-06-28 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 28, 21, 1, 6, 479701, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
